"use client";

import { useEffect, useRef, useState } from "react";

/**
 * CursorPointer — browser-only fallback for the native PyQt6
 * PointerOverlay. Listens for ``point`` WS frames (delivered to
 * the parent via the ``points`` prop, fed from the same onEvent
 * dispatcher in ``page.tsx``) and renders an animated chevron +
 * label flag clamped to the **viewport**.
 *
 * Coordinate caveat: backend points are in **global macOS screen
 * pixels** because they're meant to drive a desktop overlay that
 * paints anywhere. The browser tab is a sub-rectangle of the
 * screen (Chrome chrome, OS menu bar, dev tools, etc.). We expose
 * two strategies:
 *
 *   - ``mode="screen"``: assume the page covers (close to) the whole
 *     primary screen — translate by subtracting ``window.screenX``
 *     and ``window.screenY``. Best when the user has the browser
 *     full-screen.
 *
 *   - ``mode="proportional"`` (default): scale the point's relative
 *     position within ``window.screen`` to the viewport. Always
 *     produces a visible target even when the browser is windowed,
 *     at the cost of ~20-50 px of accuracy.
 *
 * The native overlay daemon is still the canonical surface — this
 * component is the demo-safe fallback when Edouard hasn't started
 * ``python -m overlay``.
 */

export type PointEvent = {
  // Stable id per event so React can re-mount on identical (x,y)
  // and re-trigger the animation. Generated by the parent.
  id: number;
  x: number;
  y: number;
  label?: string | null;
};

export type CursorPointerProps = {
  /** Latest point event; null = nothing to show. */
  point: PointEvent | null;
  /** How long to keep the pointer visible after each event. */
  durationMs?: number;
  /** Coordinate translation strategy. Default "proportional". */
  mode?: "screen" | "proportional";
};

const DEFAULT_DURATION = 4000;

function translatePoint(
  pt: PointEvent,
  mode: "screen" | "proportional"
): { x: number; y: number } {
  if (typeof window === "undefined") return { x: pt.x, y: pt.y };
  const screen = window.screen;
  if (mode === "screen") {
    return {
      x: pt.x - (window.screenX || 0),
      y: pt.y - (window.screenY || 0),
    };
  }
  // Proportional: map (0, 0) → (0, 0) and (screen.w, screen.h) → (vw, vh).
  const vw = window.innerWidth;
  const vh = window.innerHeight;
  const sw = Math.max(1, screen?.width || vw);
  const sh = Math.max(1, screen?.height || vh);
  return {
    x: Math.round((pt.x / sw) * vw),
    y: Math.round((pt.y / sh) * vh),
  };
}

export function CursorPointer({
  point,
  durationMs = DEFAULT_DURATION,
  mode = "proportional",
}: CursorPointerProps) {
  const [active, setActive] = useState<PointEvent | null>(null);
  const [translated, setTranslated] = useState<{ x: number; y: number } | null>(
    null
  );
  const hideTimerRef = useRef<number | null>(null);

  useEffect(() => {
    if (!point) return;
    const xy = translatePoint(point, mode);
    setActive(point);
    setTranslated(xy);
    if (hideTimerRef.current !== null) {
      window.clearTimeout(hideTimerRef.current);
    }
    hideTimerRef.current = window.setTimeout(() => {
      setActive(null);
      setTranslated(null);
      hideTimerRef.current = null;
    }, durationMs);
    return () => {
      if (hideTimerRef.current !== null) {
        window.clearTimeout(hideTimerRef.current);
        hideTimerRef.current = null;
      }
    };
  }, [point, durationMs, mode]);

  if (!active || !translated) return null;

  // Clamp so the flag stays inside the viewport even if the point is
  // near an edge.
  const vw = typeof window !== "undefined" ? window.innerWidth : 1920;
  const vh = typeof window !== "undefined" ? window.innerHeight : 1080;
  const cx = Math.max(40, Math.min(vw - 40, translated.x));
  const cy = Math.max(40, Math.min(vh - 40, translated.y));

  return (
    <div
      key={active.id}
      aria-hidden
      className="pointer-events-none fixed z-[70]"
      style={{ left: 0, top: 0, width: "100vw", height: "100vh" }}
    >
      {/* Concentric expanding rings — three offset by 1/3 phase. */}
      {[0, 1, 2].map((i) => (
        <span
          key={i}
          style={{
            position: "absolute",
            left: cx - 18,
            top: cy - 18,
            width: 36,
            height: 36,
            borderRadius: "50%",
            border: "2.5px solid #B05826",
            boxSizing: "border-box",
            opacity: 0,
            animation: `xiexie-pointer-ring 1.1s ease-out infinite`,
            animationDelay: `${(i * 1.1) / 3}s`,
          }}
        />
      ))}
      {/* Solid centre dot. */}
      <span
        style={{
          position: "absolute",
          left: cx - 6,
          top: cy - 6,
          width: 12,
          height: 12,
          borderRadius: "50%",
          background: "#B05826",
          boxShadow: "0 2px 6px rgba(176, 88, 38, 0.45)",
        }}
      />
      {/* Label flag offset down-right. */}
      {active.label ? (
        <span
          style={{
            position: "absolute",
            left: cx + 22,
            top: cy + 22,
            background: "rgba(251, 247, 240, 0.94)",
            color: "#3D2A1B",
            border: "1px solid rgba(176, 88, 38, 0.5)",
            borderRadius: 10,
            padding: "6px 10px",
            fontFamily:
              "var(--font-inter), Inter, ui-sans-serif, system-ui, sans-serif",
            fontSize: 13,
            fontWeight: 600,
            lineHeight: 1.2,
            whiteSpace: "nowrap",
            boxShadow: "0 6px 18px rgba(176, 88, 38, 0.18)",
            animation: "xiexie-pointer-flag-in 220ms ease-out both",
          }}
        >
          {active.label}
        </span>
      ) : null}
      <style jsx global>{`
        @keyframes xiexie-pointer-ring {
          0% {
            transform: scale(0.65);
            opacity: 0.85;
          }
          100% {
            transform: scale(2.0);
            opacity: 0;
          }
        }
        @keyframes xiexie-pointer-flag-in {
          0% {
            transform: translate(-6px, -4px) scale(0.9);
            opacity: 0;
          }
          100% {
            transform: translate(0, 0) scale(1);
            opacity: 1;
          }
        }
      `}</style>
    </div>
  );
}
